version: '3.4'

networks:
  apidb:
    driver: bridge 
  apifront:
    driver: bridge 
services:
  carsdb:
    container_name: Database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - apidb
  api:
    container_name: Api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 8001:443
    depends_on:
      - carsdb
    environment:
      - DB_HOST=carsdb
      - DB_NAME=CarsDb
      - DB_SA_PASWWORD=password@12345#
    networks:
      - apidb      
      - apifront
  frontend:
    container_name: Frontend
    build: ./frontend
    volumes:
      - './frontend:/app'
    ports:
      - 4500:4500
    depends_on:
      - api
    networks:
      - apifront

