version: '3.4'

networks:
  angularcrud:
    driver: bridge 
services:
  carsdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - angularcrud
  frontapi:
    container_name: AngularCrudApp
    image: ${DOCKER_REGISTRY-}frontapi
    build:
      context: .
      dockerfile: FrontApi/Dockerfile
    ports:
      - 8001:443
    depends_on:
      - carsdb
    environment:
      - DB_HOST=carsdb
      - DB_NAME=CarsDb
      - DB_SA_PASWWORD=password@12345#
    networks:
      - angularcrud
